### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by sonicx180** [codingMASTER398/clean-replit-auth#1]
How do you access the cookie in the backend? I checked the cookie and there is a value like J_qayg5RJoRGqwkdp9HxIg9nCrOi7pZL3ncsPrOHj_lpLlAg.

What is that for ?

**Comment by codingMASTER398** [comment]
https://docs.replit.com/hosting/authenticating-users-repl-auth#retrieving-information-from-the-authenticated-account

**Comment by sonicx180** [comment]
thanks!
